# Generated by Django 4.2.4 on 2023-08-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='my study', max_length=100)),
                ('ethics', models.TextField(max_length=4096)),
                ('researchers', models.ManyToManyField(to='researcher.researcher')),
            ],
        ),
    ]
